"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Cargar variables de entorno desde .env
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv no está instalado, usar variables del sistema

BASE_DIR = Path(__file__).resolve().parent.parent.parent

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev-only-change-me")
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() == "true"
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(
    ",") if os.getenv("DJANGO_ALLOWED_HOSTS") else []

# Dataverse
DATAVERSE_URL = os.getenv("DATAVERSE_URL", "").rstrip("/")
DATAVERSE_TENANT_ID = os.getenv("DATAVERSE_TENANT_ID", "")
DATAVERSE_CLIENT_ID = os.getenv("DATAVERSE_CLIENT_ID", "")
DATAVERSE_CLIENT_SECRET = os.getenv("DATAVERSE_CLIENT_SECRET", "")
DATAVERSE_API_VERSION = os.getenv("DATAVERSE_API_VERSION", "v9.2")
DATAVERSE_TIMEOUT = int(os.getenv("DATAVERSE_TIMEOUT", "30"))

# Selector de backend de persistencia:
#   "sqlite"    → base de datos local SQLite (por defecto, desarrollo)
#   "dataverse" → Microsoft Dataverse vía Web API OData v4
PERSISTENCE_BACKEND = os.getenv("PERSISTENCE_BACKEND", "sqlite")

# Endpoints de diagnóstico internos.
# Siempre deshabilitados por defecto: se habilitan solo con flag explícito.
ENABLE_DEV_DIAGNOSTICS = os.getenv(
    "ENABLE_DEV_DIAGNOSTICS",
    "false",
).lower() == "true"

# Cache JSON para consulta jefatura en backend Dataverse
try:
    CONSULTA_DATAVERSE_CACHE_TTL_SECONDS = int(
        os.getenv("CONSULTA_DATAVERSE_CACHE_TTL_SECONDS", "3600")
    )
except ValueError:
    CONSULTA_DATAVERSE_CACHE_TTL_SECONDS = 3600
CONSULTA_DATAVERSE_CACHE_FILE = os.getenv(
    "CONSULTA_DATAVERSE_CACHE_FILE",
    str(BASE_DIR / ".cache" / "consulta_dataverse.json"),
)

# Django cache framework
# Por defecto: LocMemCache (sin dependencias externas, válido para dev y procesos únicos).
# Para producción multi-worker sobreescribir con Redis en settings/production.py:
#   CACHES["dataverse"]["BACKEND"] = "django.core.cache.backends.redis.RedisCache"
#   CACHES["dataverse"]["LOCATION"] = os.getenv("REDIS_URL", "redis://localhost:6379/1")
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "calipro-default",
    },
    # Cache dedicado para lookups Dataverse (TTL corto, aislado del cache general)
    "dataverse": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "calipro-dataverse",
    },
}

# Backends de autenticación:
#   - CaliProAuthBackend: fuente de verdad en ambos modos (SQLite y Dataverse)
#   - ModelBackend: fallback SOLO en modo sqlite, para bootstrap via createsuperuser.
#     En modo dataverse se excluye para evitar que credenciales Django nativas
#     omitan la verificación contra crf21_usuariooperativos.
AUTHENTICATION_BACKENDS = ["usuarios.auth_backend.CaliProAuthBackend"]
if PERSISTENCE_BACKEND.lower().strip() == "sqlite":
    AUTHENTICATION_BACKENDS.append("django.contrib.auth.backends.ModelBackend")

LANGUAGE_CODE = "es-cl"
TIME_ZONE = os.getenv("TIME_ZONE", "America/Santiago")
USE_I18N = True
USE_TZ = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
    'operaciones',
    'usuarios',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.DataversePerfMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [

    {

        "BACKEND": "django.template.backends.django.DjangoTemplates",

        # DIRS: templates/ compartidos (base.html, layout_app.html)

        "DIRS": [BASE_DIR / "templates"],

        # APP_DIRS: busca templates/ dentro de cada app instalada

        "APP_DIRS": True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.debug",

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

                # AGREGAR: inyecta planta, exportador, nav a todos los templates

                "core.context_processors.CaliPro_context",

            ],

        },

    },

]

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
LOGIN_URL = "/usuarios/login/"

LOGIN_REDIRECT_URL = "/usuarios/portal/"

LOGOUT_REDIRECT_URL = "/usuarios/login/"


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'
