# Generated by Django 6.0.3 on 2026-03-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50)),
                ('source_event_id', models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120)),
                ('operator_code', models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50)),
                ('temporada', models.CharField(db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('dataverse_id', models.CharField(blank=True, db_index=True, help_text='GUID o identificador equivalente en Dataverse.', max_length=120, null=True)),
                ('bin_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'operaciones_bin',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['temporada', 'bin_code'], name='ix_bin_temp_code')],
                'constraints': [models.UniqueConstraint(fields=('temporada', 'bin_code'), name='uq_bin_temporada_code')],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50)),
                ('source_event_id', models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120)),
                ('operator_code', models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50)),
                ('temporada', models.CharField(db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('dataverse_id', models.CharField(blank=True, db_index=True, help_text='GUID o identificador equivalente en Dataverse.', max_length=120, null=True)),
                ('lote_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'operaciones_lote',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['temporada', 'lote_code'], name='ix_lote_temp_code')],
                'constraints': [models.UniqueConstraint(fields=('temporada', 'lote_code'), name='uq_lote_temporada_code')],
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50)),
                ('source_event_id', models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120)),
                ('operator_code', models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50)),
                ('temporada', models.CharField(db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('dataverse_id', models.CharField(blank=True, db_index=True, help_text='GUID o identificador equivalente en Dataverse.', max_length=120, null=True)),
                ('pallet_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'operaciones_pallet',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['temporada', 'pallet_code'], name='ix_pallet_temp_code')],
                'constraints': [models.UniqueConstraint(fields=('temporada', 'pallet_code'), name='uq_pallet_temporada_code')],
            },
        ),
        migrations.CreateModel(
            name='BinLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50)),
                ('source_event_id', models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120)),
                ('operator_code', models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bin_lotes', to='operaciones.bin')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bin_lotes', to='operaciones.lote')),
            ],
            options={
                'db_table': 'operaciones_bin_lote',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bin', 'lote'], name='ix_bin_lote_pair'), models.Index(fields=['lote'], name='ix_bin_lote_lote')],
                'constraints': [models.UniqueConstraint(fields=('bin', 'lote'), name='uq_bin_lote_pair')],
            },
        ),
        migrations.CreateModel(
            name='PalletLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50)),
                ('source_event_id', models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120)),
                ('operator_code', models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallet_lotes', to='operaciones.lote')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pallet_lotes', to='operaciones.pallet')),
            ],
            options={
                'db_table': 'operaciones_pallet_lote',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pallet', 'lote'], name='ix_pallet_lote_pair'), models.Index(fields=['lote'], name='ix_pallet_lote_lote')],
                'constraints': [models.UniqueConstraint(fields=('pallet', 'lote'), name='uq_pallet_lote_pair')],
            },
        ),
        migrations.CreateModel(
            name='RegistroEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50)),
                ('source_event_id', models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120)),
                ('operator_code', models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50)),
                ('temporada', models.CharField(db_index=True, max_length=20)),
                ('event_key', models.CharField(db_index=True, help_text='Clave idempotente única del evento.', max_length=120, unique=True)),
                ('tipo_evento', models.CharField(choices=[('BIN_REGISTRADO', 'Bin registrado'), ('LOTE_CREADO', 'Lote creado'), ('BIN_ASIGNADO_LOTE', 'Bin asignado a lote'), ('LOTE_INGRESO_CAMARA', 'Lote ingresa a cámara'), ('LOTE_SALIDA_CAMARA', 'Lote sale de cámara'), ('PALLET_CREADO', 'Pallet creado'), ('LOTE_ASIGNADO_PALLET', 'Lote asignado a pallet'), ('ETAPA_REGISTRADA', 'Etapa registrada')], db_index=True, max_length=40)),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, help_text='Momento real del evento operacional.', null=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Metadatos flexibles del evento.')),
                ('notes', models.TextField(blank=True, default='')),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_etapa', to='operaciones.bin')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_etapa', to='operaciones.lote')),
                ('pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_etapa', to='operaciones.pallet')),
            ],
            options={
                'db_table': 'operaciones_registro_etapa',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['temporada', 'tipo_evento'], name='ix_reg_temp_tipo'), models.Index(fields=['occurred_at'], name='ix_reg_occurred_at'), models.Index(fields=['bin'], name='ix_reg_bin'), models.Index(fields=['lote'], name='ix_reg_lote'), models.Index(fields=['pallet'], name='ix_reg_pallet')],
                'constraints': [models.CheckConstraint(condition=models.Q(('bin__isnull', False), ('lote__isnull', False), ('pallet__isnull', False), _connector='OR'), name='ck_registro_etapa_target_present')],
            },
        ),
    ]
