# Generated by Django 6.0.3 on 2026-03-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_alter_registroetapa_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroetapa',
            name='tipo_evento',
            field=models.CharField(choices=[('BIN_REGISTRADO', 'Bin registrado'), ('LOTE_CREADO', 'Lote creado'), ('PALLET_CREADO', 'Pallet creado'), ('LOTE_ASIGNADO_PALLET', 'Lote asignado a pallet'), ('PALLET_CERRADO', 'Pallet cerrado')], db_index=True, max_length=40),
        ),
    ]
