# Generated by Django 6.0.3 on 2026-03-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_alter_registroetapa_tipo_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroetapa',
            name='tipo_evento',
            field=models.CharField(choices=[('BIN_REGISTRADO', 'Bin registrado'), ('LOTE_CREADO', 'Lote creado'), ('PALLET_CREADO', 'Pallet creado'), ('LOTE_ASIGNADO_PALLET', 'Lote asignado a pallet'), ('PALLET_CERRADO', 'Pallet cerrado'), ('PESAJE', 'Pesaje y asignación de lote'), ('DESVERDIZADO_INGRESO', 'Ingreso a desverdizado'), ('DESVERDIZADO_SALIDA', 'Salida de desverdizado'), ('CAMARA_MANTENCION', 'Ingreso a cámara de mantención'), ('CAMARA_MANTENCION_SALIDA', 'Salida de cámara de mantención'), ('PACKING_PROCESO', 'Proceso de packing'), ('CONTROL_CALIDAD', 'Control de calidad'), ('CAMARA_FRIO_INGRESO', 'Ingreso a cámara de frío'), ('CONTROL_TEMPERATURA', 'Control de temperatura en cámara')], db_index=True, max_length=40),
        ),
    ]
