# Generated by Django 6.0.3 on 2026-03-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_add_new_entities_and_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='bin_code',
            field=models.CharField(help_text='Codigo de barras del bin (del modulo campo o formado en recepcion)', max_length=50),
        ),
        migrations.AlterField(
            model_name='calidaddesverdizado',
            name='aprobado',
            field=models.BooleanField(blank=True, help_text='Aprobado para ingreso a packing', null=True),
        ),
        migrations.AlterField(
            model_name='calidaddesverdizado',
            name='operator_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50),
        ),
        migrations.AlterField(
            model_name='calidaddesverdizado',
            name='source_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120),
        ),
        migrations.AlterField(
            model_name='calidaddesverdizado',
            name='source_system',
            field=models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='calidaddesverdizado',
            name='temperatura_fruta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='°C', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='calidadpallet',
            name='aprobado',
            field=models.BooleanField(blank=True, help_text='Aprobado para ingreso a camara de frio', null=True),
        ),
        migrations.AlterField(
            model_name='calidadpallet',
            name='operator_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50),
        ),
        migrations.AlterField(
            model_name='calidadpallet',
            name='peso_caja_muestra',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='kg', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='calidadpallet',
            name='source_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120),
        ),
        migrations.AlterField(
            model_name='calidadpallet',
            name='source_system',
            field=models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='calidadpallet',
            name='temperatura_fruta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='°C', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='camarafrio',
            name='hora_salida',
            field=models.CharField(blank=True, default='', help_text='Nullable. Restriccion: no puede ser anterior a hora_ingreso', max_length=5),
        ),
        migrations.AlterField(
            model_name='camarafrio',
            name='humedad_relativa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='%', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='camarafrio',
            name='operator_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50),
        ),
        migrations.AlterField(
            model_name='camarafrio',
            name='source_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120),
        ),
        migrations.AlterField(
            model_name='camarafrio',
            name='source_system',
            field=models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='camarafrio',
            name='temperatura_camara',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='°C', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='camaramantencion',
            name='hora_salida',
            field=models.CharField(blank=True, default='', help_text='Nullable. Restriccion: no puede ser anterior a hora_ingreso', max_length=5),
        ),
        migrations.AlterField(
            model_name='camaramantencion',
            name='humedad_relativa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='%', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='camaramantencion',
            name='operator_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50),
        ),
        migrations.AlterField(
            model_name='camaramantencion',
            name='source_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120),
        ),
        migrations.AlterField(
            model_name='camaramantencion',
            name='source_system',
            field=models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='camaramantencion',
            name='temperatura_camara',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='°C', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='controlprocesopacking',
            name='operator_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50),
        ),
        migrations.AlterField(
            model_name='controlprocesopacking',
            name='pct_calibre_export',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% — rango 0-100', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='controlprocesopacking',
            name='pct_calibres_menores',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% — rango 0-100', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='controlprocesopacking',
            name='ph_agua',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Escala 0-14', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='controlprocesopacking',
            name='rendimiento_lote_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% — rango 0-100', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='controlprocesopacking',
            name='source_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120),
        ),
        migrations.AlterField(
            model_name='controlprocesopacking',
            name='source_system',
            field=models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='controlprocesopacking',
            name='temp_agua_tina',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='°C', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='controlprocesopacking',
            name='temp_aire_secado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='°C', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='controlprocesopacking',
            name='temp_cera',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='°C', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='controlprocesopacking',
            name='tiempo_inmersion_seg',
            field=models.IntegerField(blank=True, help_text='Segundos enteros', null=True),
        ),
        migrations.AlterField(
            model_name='controlprocesopacking',
            name='velocidad_volcador',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='bins/h', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='desverdizado',
            name='hora_salida',
            field=models.CharField(blank=True, default='', help_text='Nullable. Restriccion: no puede ser anterior a hora_ingreso', max_length=5),
        ),
        migrations.AlterField(
            model_name='desverdizado',
            name='operator_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50),
        ),
        migrations.AlterField(
            model_name='desverdizado',
            name='proceso',
            field=models.CharField(blank=True, default='', help_text='Metodo de conservacion — texto libre por ahora', max_length=100),
        ),
        migrations.AlterField(
            model_name='desverdizado',
            name='source_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120),
        ),
        migrations.AlterField(
            model_name='desverdizado',
            name='source_system',
            field=models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingresoapacking',
            name='operator_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingresoapacking',
            name='source_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120),
        ),
        migrations.AlterField(
            model_name='ingresoapacking',
            name='source_system',
            field=models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingresoapacking',
            name='via_desverdizado',
            field=models.BooleanField(default=False, help_text='True = llego desde desverdizado / False = directo'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='disponibilidad_camara_desverdizado',
            field=models.CharField(blank=True, choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible'), ('no_aplica', 'No aplica')], help_text='Nullable. Solo aplica si requiere_desverdizado=True. Tres estados: disponible / no_disponible / no_aplica', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mediciontemperaturasalida',
            name='dentro_rango',
            field=models.BooleanField(blank=True, help_text='Si esta dentro del rango aceptable', null=True),
        ),
        migrations.AlterField(
            model_name='mediciontemperaturasalida',
            name='operator_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediciontemperaturasalida',
            name='punto_medicion',
            field=models.CharField(blank=True, default='', help_text='Descripcion del punto donde se tomo la medicion', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediciontemperaturasalida',
            name='source_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120),
        ),
        migrations.AlterField(
            model_name='mediciontemperaturasalida',
            name='source_system',
            field=models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediciontemperaturasalida',
            name='temperatura_pallet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='°C — temperatura superficial del pallet', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='registroetapa',
            name='event_key',
            field=models.CharField(db_index=True, help_text='Clave idempotente unica del evento.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='registropacking',
            name='categoria_calidad',
            field=models.CharField(blank=True, default='', help_text='Texto libre por ahora', max_length=50),
        ),
        migrations.AlterField(
            model_name='registropacking',
            name='linea_proceso',
            field=models.CharField(blank=True, default='', help_text='Texto libre — pendiente aclarar con cliente', max_length=50),
        ),
        migrations.AlterField(
            model_name='registropacking',
            name='merma_seleccion_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rango 0-100', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='registropacking',
            name='operator_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50),
        ),
        migrations.AlterField(
            model_name='registropacking',
            name='source_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120),
        ),
        migrations.AlterField(
            model_name='registropacking',
            name='source_system',
            field=models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50),
        ),
    ]
