# Generated by Django 6.0.3 on 2026-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_lote_estado_temporada_sequence_pallet_lote_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='temporada_codigo',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Codigo de temporada operativa. Ej: 2025-2026. Derivado automaticamente si no se provee.', max_length=20),
        ),
    ]
