# Generated by Django 6.0.3 on 2026-03-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_desverdizado_horas_calidad_pallet_muestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='calidadpalletmuestra',
            name='source_event_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Identificador externo del evento o registro origen.', max_length=120),
        ),
        migrations.AlterField(
            model_name='calidadpalletmuestra',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='calidadpalletmuestra',
            name='operator_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código del operador responsable de la acción.', max_length=50),
        ),
        migrations.AlterField(
            model_name='calidadpalletmuestra',
            name='source_system',
            field=models.CharField(blank=True, default='local', help_text='Sistema origen del registro: local, dataverse, import, api, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='desverdizado',
            name='proceso',
            field=models.CharField(blank=True, default='', help_text="Metodo de conservacion — texto libre. Valor legacy: horas en formato '72h'.", max_length=100),
        ),
    ]
