# Generated by Django 6.0.3 on 2026-04-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_add_planillas_calidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='desverdizado',
            name='numero_camara',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
