# Generated by Django 6.0.3 on 2026-04-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_desverdizado_numero_camara'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='cantidad_bins_grupo',
            field=models.IntegerField(blank=True, help_text='Cantidad de bins del mismo tipo en el grupo pesado', null=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='tara_bin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tara especifica del tipo de bin (kg)', max_digits=8, null=True),
        ),
    ]
