# Generated by Django 6.0.3 on 2026-04-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0013_add_tara_bin_cantidad_bins_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropacking',
            name='kilos_descarte_local',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilos descartados o destinados a consumo local', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registropacking',
            name='kilos_fruta_comercial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilos disponibles para venta comercial', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registropacking',
            name='merma_seleccion_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Merma de seleccion en kilos', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='registropacking',
            name='merma_seleccion_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(%) — deprecated, usar merma_seleccion_kg', max_digits=5, null=True),
        ),
    ]
