# Generated by Django 6.0.3 on 2026-04-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuarioprofile',
            name='rol',
            field=models.CharField(blank=True, help_text='Ej: "Recepcion, Pesaje" o "Administrador"', max_length=500, verbose_name='Roles separados por coma (crf21_rol)'),
        ),
    ]
